# Generated by Django 6.0.4 on 2026-04-28 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.IntegerField(db_column='idPersona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
                ('apellido', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
                ('correo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=80)),
                ('fecha_registro', models.DateField()),
                ('genero', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('contrasenia', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('verificado', models.BooleanField()),
                ('paisdeorigen', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='paisDeOrigen', max_length=50)),
                ('fechadenacimiento', models.DateField(db_column='fechaDeNacimiento')),
            ],
            options={
                'db_table': 'Persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('idsuscripcion', models.IntegerField(db_column='idSuscripcion', primary_key=True, serialize=False)),
                ('tiposuscripcion', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='tipoSuscripcion', max_length=20)),
                ('fechainiciosuscripcion', models.DateTimeField(db_column='fechaInicioSuscripcion')),
                ('estadosuscripcion', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='estadoSuscripcion', max_length=20)),
            ],
            options={
                'db_table': 'Suscripcion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.IntegerField(db_column='id_Pago', primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('metodo_pago', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='metodo_Pago', max_length=30)),
                ('estado_pago', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='estado_Pago', max_length=30)),
                ('suscripcion', models.ForeignKey(db_column='suscripcion_idsuscripcion', on_delete=django.db.models.deletion.DO_NOTHING, to='users.suscripcion')),
            ],
            options={
                'db_table': 'Pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('tipodecuenta', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='tipoDeCuenta', max_length=12)),
                ('idpersona', models.ForeignKey(db_column='idPersona', on_delete=django.db.models.deletion.DO_NOTHING, to='users.persona')),
                ('suscripcion', models.ForeignKey(db_column='Suscripcion_idSuscripcion', on_delete=django.db.models.deletion.DO_NOTHING, to='users.suscripcion')),
            ],
            options={
                'db_table': 'Usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarioartista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificaciones_activas', models.BooleanField()),
                ('fecha_inicio_seguimiento', models.DateField()),
                ('artista', models.ForeignKey(db_column='Artista_idPersona', on_delete=django.db.models.deletion.DO_NOTHING, to='music.artista')),
                ('usuario', models.ForeignKey(db_column='Usuario_idPersona', on_delete=django.db.models.deletion.DO_NOTHING, to='users.usuario')),
            ],
            options={
                'db_table': 'UsuarioArtista',
                'managed': True,
            },
        ),
    ]
