# Generated by Django 6.0.4 on 2026-04-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('idartista', models.IntegerField(db_column='idArtista', primary_key=True, serialize=False)),
                ('biografia', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
            ],
            options={
                'db_table': 'Artista',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Artistagenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ArtistaGenero',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('idcancion', models.IntegerField(db_column='idCancion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('duracion', models.IntegerField()),
                ('numerodepista', models.IntegerField(db_column='NumeroDePista')),
                ('url_audio', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('reproducciones', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cancion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Discografica',
            fields=[
                ('iddiscografica', models.IntegerField(db_column='idDiscografica', primary_key=True, serialize=False)),
                ('nombrediscografica', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='nombreDiscografica', max_length=35)),
            ],
            options={
                'db_table': 'Discografica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idgenero', models.IntegerField(db_column='idGenero', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=80)),
            ],
            options={
                'db_table': 'Genero',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lanzamiento',
            fields=[
                ('idlanzamiento', models.IntegerField(db_column='idLanzamiento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Nombre', max_length=60)),
                ('fechadepublicacion', models.DateField(db_column='FechaDePublicacion')),
                ('tipodelanzamiento', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='tipoDeLanzamiento', max_length=15)),
                ('urlportadalanzamiento', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='urlPortadaLanzamiento', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Lanzamiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('idplaylist', models.IntegerField(db_column='idPlaylist', primary_key=True, serialize=False)),
                ('nombreplaylist', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='nombrePlaylist', max_length=30)),
            ],
            options={
                'db_table': 'Playlist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Regalias',
            fields=[
                ('id_regalia', models.IntegerField(db_column='id_Regalia', primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'Regalias',
                'managed': True,
            },
        ),
    ]
