# Generated by Django 6.0.4 on 2026-04-28 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='idpersona',
            field=models.ForeignKey(db_column='idPersona', on_delete=django.db.models.deletion.DO_NOTHING, to='users.persona'),
        ),
        migrations.AddField(
            model_name='artistagenero',
            name='artista',
            field=models.ForeignKey(db_column='Artista_idPersona', on_delete=django.db.models.deletion.DO_NOTHING, to='music.artista'),
        ),
        migrations.AddField(
            model_name='artista',
            name='discografica',
            field=models.ForeignKey(db_column='Discografica_idDiscografica', on_delete=django.db.models.deletion.DO_NOTHING, to='music.discografica'),
        ),
        migrations.AddField(
            model_name='artistagenero',
            name='genero',
            field=models.ForeignKey(db_column='Genero_idGenero', on_delete=django.db.models.deletion.DO_NOTHING, to='music.genero'),
        ),
        migrations.AddField(
            model_name='lanzamiento',
            name='artista',
            field=models.ForeignKey(db_column='idArtista', on_delete=django.db.models.deletion.DO_NOTHING, to='music.artista'),
        ),
        migrations.AddField(
            model_name='lanzamiento',
            name='genero',
            field=models.ForeignKey(blank=True, db_column='Genero_idGenero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.genero'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='lanzamiento',
            field=models.ForeignKey(db_column='Lanzamiento_idLanzamiento', on_delete=django.db.models.deletion.DO_NOTHING, to='music.lanzamiento'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='usuario',
            field=models.ForeignKey(db_column='Usuario_idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='users.usuario'),
        ),
        migrations.AddField(
            model_name='regalias',
            name='artista',
            field=models.ForeignKey(db_column='Artista_idArtista', on_delete=django.db.models.deletion.DO_NOTHING, to='music.artista'),
        ),
        migrations.AddField(
            model_name='regalias',
            name='cancion',
            field=models.ForeignKey(db_column='Cancion_idCancion', on_delete=django.db.models.deletion.DO_NOTHING, to='music.cancion'),
        ),
    ]
